### ISSUE TITLE
Using HttpClient with the using statement is not the best choice

### ISSUE THREAD

**Issue by wxtsxt** [severisv/SlackLogger#12]
In .net core using HttpClient with the using statement is not the best choice as described here https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

I think we can have an HttpClient created by DI container and passed to constructor.
The other option is to get HttpClientFactory in constructor and create HttpClient class every time we need it `httpClientFactory.Create()`, but not dispose them. HttpClientFactory takes care of the lifetime of created HttpClients.

Do you care for any option? Would you like me to do it?

**Comment by severisv** [comment]
I like the idea of using `HttpClientFactory`, but that would require us to register an `HttpClient` or `HttpClientFactory` here https://github.com/severisv/SlackLogger/blob/master/SlackLogger/Configuration.cs, wouldn't it? 

Is that viable, or too intrusive? 

Any thoughts @phillijw  ?

**Comment by phillijw** [comment]
I think this would be a good idea (I actually thought about changing this myself). I'm not sure what the best way is yet to actually implement it. It would be nice if it were backwards compatible as well.

In an app I have right now, I'm using HttpClientFactory with named clients for some other stuff. I am trying to envision what would happen if we passed in the factory to AddSlack configuration methods (either directly or via the configure action). Would we want to specify a named client? Would we just use the default unnamed client? We might have to think about these details a little more before diving into an implementation.

**Comment by wxtsxt** [comment]
Named clients are setup in Startup.cs, which I do not want client to extend. 

I would pass a default http client to SlackService.
SlackService is created not from DI but from Logger class. Therefore I would pass HttpClientFactory to the Logger constructor and keep it there as a private member. 

Right now we create a new instance of Logger every time from the LoggerProvider. It is possible in future to cache a logger instance if we make it thread safe.

**Comment by wxtsxt** [comment]
We should not instantiate HttpClient with every call to Slack. https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netcore-3.1#remarks

It is impossible to get IHttpClientFactory from the DI container in a logger provider as it causes a log message to be sent and ends up with StackOverflowException.
https://stackoverflow.com/questions/52083818/how-can-i-prevent-httpclient-via-ihttpclientfactory-from-logging-to-ilogger/52085851

The easiest thing is to create a single static HttpClient for the SlackLogger. The PostAsync method is thread safe. I will propose a MR.

There is yet another alternative to use SocketsHttpHandler, but it is implemented in .net core only (not .netstandard)
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#alternatives-to-ihttpclientfactory

**Comment by phillijw** [comment]
I think a static HttpClient is fine. The only downside I remember is the DNS not refreshing but I think that is fixed in newer versions.
