### ISSUE TITLE
Queue repeated exception log entries

### ISSUE THREAD

**Issue by wxtsxt** [severisv/SlackLogger#14]
Problem:
Some exception log entries happen in bulk such as: loosing database connection or other service network issues. That can cause many message entries in logs and slack.

Solution:
Group same exception log entries and cache them for a period of time before sending them to slack.

Specs (to be discussed):
- Ignore the below when no exception in the log entry.
- Make this feature off by default. Require code to turn this on.
- Always log the first appearance of an exception.
- Store every distinct exception in memory. An exception is the same when the message and call stack are the same (inner exceptions are not compared).
- Do not log a repeated exception log entry unless a specific time passed (1 minute by default). The time period is the same for all exceptions and all them all logged one by one to slack
- Count the number of log entry appearance to present it: _logged 14 times within last 1 minute_

Should be configurable:
- turning this feature on/off
- how long a message stays in cache - default 1 minute

**Comment by wxtsxt** [comment]
Let me know what you think. I will gladly implement it.

**Comment by severisv** [comment]
This is a nice idea, and the suggested implementation seems simple enough.

How would you cache it though? `IMemoryCache`? 

I must admit I'm a little skeptical of giving a logger a lot of responsibility, but if you think you can implement it safely and I don't hear other convincing concerns, I'm happy to merge :)

**Comment by phillijw** [comment]
I think this would be a nice feature as long as it can be disabled/enabled. My main concern with how it functions would be how the caching works and how "late" I would receive the aggregated info. I think you mention that you would get nothing later than 1 minute though. Is that in all circumstances or just when there is a stream of messages coming in every 2 seconds for an entire minute?

**Comment by wxtsxt** [comment]
For the feature to work we would need a queue (not exactly cache) with messages waiting to be logged and a process to go through all items to see if they match. When we hit one minute time period we would need to go over all items in the queue and remove the duplicates.
It is possible but requires memory and concurrent locks. To minimize the impact I see some tweaks that could be implemented that may not be generic enough to be implemented in a general logging library.

Therefore I take the idea back and instead create a new separete 'debounce logger' that will wrap 'slack logger'.
Debounce logger will queue repeated messages and send them to the next logger under the conditions described above. It will be a kind of log filter/queue running BEFORE the slack logger or any other logger (like some email logger).
I will research this solution. This issue may be closed.

**Comment by wxtsxt** [comment]
To create this 'debounce logger' I need to wrap SlackLogger into my logger like this
```
logging.Services
  .AddSingleton<ILoggerProvider>(provider => 
    new SlackFilterLoggerProvider(new **SlackLogger.LoggerProvider**()));
```
But The LoggerProvider is not public so I can use it my way.
Is it ok for me to make it public (and change its name to SlackLoggerProvider)?
