### ISSUE TITLE
Calling Slack with my own or without a username

### ISSUE THREAD

**Issue by wxtsxt** [severisv/SlackLogger#7]
The username is always SlackLogger sent to Slack. 
Is it possible to add a configuration with a custom username? And when a username is null or empty to not send it at all. I have a default username set in my web hook and I want to use it.
![image](https://user-images.githubusercontent.com/5221330/66647257-bae61a80-ec28-11e9-90da-ff77f1e2b716.png)

**Comment by severisv** [comment]
You can configure the name like this:

```cs
.AddSlack(options =>
                    {
                         options.WebhookUrl = "....";
                         options.ApplicationName = "Name of my choice";                        
                    })                     
```

I agree it would make sense to send nothing at all when it is it not set, so that the name of the Webhook would be used. Feel free to make a PR for it - otherwise I'll look into it when I can find the time
