### ISSUE TITLE
LogCritical(message) doesn't work when calling from a constructor

### ISSUE THREAD

**Issue by phillijw** [severisv/SlackLogger#9]
If you add the exception then it does work

**Comment by Umbralith** [comment]
Same problem, using .LogCritical(message) inside a constructor does not post to slack, but using .LogCritical(ex, message) does post to slack.

When using the .Log outside of the constructor, both methods ( .LogCritical(message) and .LogCritical(ex, message) ) post to slack

**Comment by phillijw** [comment]
While debugging, `slackService` appears to be null while calling `slackService.Log(...)` somehow. I have no idea how this is possible.

https://github.com/severisv/SlackLogger/blob/master/SlackLogger/Logger.cs#L43

I hope this is an issue with my debugger:
![image](https://user-images.githubusercontent.com/467889/66869143-58f91e00-ef64-11e9-8fa9-10a3c27f7fca.png)

**Comment by severisv** [comment]
I'm not able to reproduce this with the old version of SlackLogger (before https://github.com/severisv/SlackLogger/pull/8). Is it from just any constructor? What version of .net core are you on?

Does https://github.com/severisv/SlackLogger/pull/8 fix this for you?

**Comment by phillijw** [comment]
It's possible this was just my debugger being wonky. I'm fine with closing it as I haven't ran into that issue lately
